version: '3'
services:
  cassandra:
    image: cassandra:3.0.12
    ports:
     - "9042:9042"   # Native transport
     - "7199:7199"   # JMX
     - "9160:9160"   # Thrift clients
    networks:
     - cassnet
    restart: always
  cass_node1:
    image: cassandra:3.0.12
    depends_on:
     - cassandra
    environment:
     - CASSANDRA_SEEDS=cassandra
    networks:
     - cassnet
    restart: always
networks:
  cassnet:
